[
{"id":"Debidwar","district_id":"Comilla","name":"Debidwar","bn_name":"দেবিদ্বার","url":"debidwar.comilla.gov.bd"},
{"id":"Barura","district_id":"Comilla","name":"Barura","bn_name":"বরুড়া","url":"barura.comilla.gov.bd"},
{"id":"Brahmanpara","district_id":"Comilla","name":"Brahmanpara","bn_name":"ব্রাহ্মণপাড়া","url":"brahmanpara.comilla.gov.bd"},
{"id":"Chandina","district_id":"Comilla","name":"Chandina","bn_name":"চান্দিনা","url":"chandina.comilla.gov.bd"},
{"id":"Chauddagram","district_id":"Comilla","name":"Chauddagram","bn_name":"চৌদ্দগ্রাম","url":"chauddagram.comilla.gov.bd"},
{"id":"Daudkandi","district_id":"Comilla","name":"Daudkandi","bn_name":"দাউদকান্দি","url":"daudkandi.comilla.gov.bd"},
{"id":"Homna","district_id":"Comilla","name":"Homna","bn_name":"হোমনা","url":"homna.comilla.gov.bd"},
{"id":"Laksam","district_id":"Comilla","name":"Laksam","bn_name":"লাকসাম","url":"laksam.comilla.gov.bd"},
{"id":"Muradnagar","district_id":"Comilla","name":"Muradnagar","bn_name":"মুরাদনগর","url":"muradnagar.comilla.gov.bd"},
{"id":"Nangalkot","district_id":"Comilla","name":"Nangalkot","bn_name":"নাঙ্গলকোট","url":"nangalkot.comilla.gov.bd"},
{"id":"ComillaSadar","district_id":"Comilla","name":"Comilla Sadar","bn_name":"কুমিল্লা সদর","url":"comillasadar.comilla.gov.bd"},
{"id":"Meghna","district_id":"Comilla","name":"Meghna","bn_name":"মেঘনা","url":"meghna.comilla.gov.bd"},
{"id":"Monohargonj","district_id":"Comilla","name":"Monohargonj","bn_name":"মনোহরগঞ্জ","url":"monohargonj.comilla.gov.bd"},
{"id":"Sadarsouth","district_id":"Comilla","name":"Sadarsouth","bn_name":"সদর দক্ষিণ","url":"sadarsouth.comilla.gov.bd"},
{"id":"Titas","district_id":"Comilla","name":"Titas","bn_name":"তিতাস","url":"titas.comilla.gov.bd"},
{"id":"Burichang","district_id":"Comilla","name":"Burichang","bn_name":"বুড়িচং","url":"burichang.comilla.gov.bd"},
{"id":"Lalmai","district_id":"Comilla","name":"Lalmai","bn_name":"লালমাই","url":"lalmai.comilla.gov.bd"},
{"id":"Chhagalnaiya","district_id":"Feni","name":"Chhagalnaiya","bn_name":"ছাগলনাইয়া","url":"chhagalnaiya.feni.gov.bd"},
{"id":"FeniSadar","district_id":"Feni","name":"Feni Sadar","bn_name":"ফেনী সদর","url":"sadar.feni.gov.bd"},
{"id":"Sonagazi","district_id":"Feni","name":"Sonagazi","bn_name":"সোনাগাজী","url":"sonagazi.feni.gov.bd"},
{"id":"Fulgazi","district_id":"Feni","name":"Fulgazi","bn_name":"ফুলগাজী","url":"fulgazi.feni.gov.bd"},
{"id":"Parshuram","district_id":"Feni","name":"Parshuram","bn_name":"পরশুরাম","url":"parshuram.feni.gov.bd"},
{"id":"Daganbhuiyan","district_id":"Feni","name":"Daganbhuiyan","bn_name":"দাগনভূঞা","url":"daganbhuiyan.feni.gov.bd"},
{"id":"BrahmanbariaSadar","district_id":"Brahmanbaria","name":"Brahmanbaria Sadar","bn_name":"ব্রাহ্মণবাড়িয়া সদর","url":"sadar.brahmanbaria.gov.bd"},
{"id":"Kasba","district_id":"Brahmanbaria","name":"Kasba","bn_name":"কসবা","url":"kasba.brahmanbaria.gov.bd"},
{"id":"Nasirnagar","district_id":"Brahmanbaria","name":"Nasirnagar","bn_name":"নাসিরনগর","url":"nasirnagar.brahmanbaria.gov.bd"},
{"id":"Sarail","district_id":"Brahmanbaria","name":"Sarail","bn_name":"সরাইল","url":"sarail.brahmanbaria.gov.bd"},
{"id":"Ashuganj","district_id":"Brahmanbaria","name":"Ashuganj","bn_name":"আশুগঞ্জ","url":"ashuganj.brahmanbaria.gov.bd"},
{"id":"Akhaura","district_id":"Brahmanbaria","name":"Akhaura","bn_name":"আখাউড়া","url":"akhaura.brahmanbaria.gov.bd"},
{"id":"Nabinagar","district_id":"Brahmanbaria","name":"Nabinagar","bn_name":"নবীনগর","url":"nabinagar.brahmanbaria.gov.bd"},
{"id":"Bancharampur","district_id":"Brahmanbaria","name":"Bancharampur","bn_name":"বাঞ্ছারামপুর","url":"bancharampur.brahmanbaria.gov.bd"},
{"id":"Bijoynagar","district_id":"Brahmanbaria","name":"Bijoynagar","bn_name":"বিজয়নগর","url":"bijoynagar.brahmanbaria.gov.bd "},
{"id":"RangamatiSadar","district_id":"Rangamati","name":"Rangamati Sadar","bn_name":"রাঙ্গামাটি সদর","url":"sadar.rangamati.gov.bd"},
{"id":"Kaptai","district_id":"Rangamati","name":"Kaptai","bn_name":"কাপ্তাই","url":"kaptai.rangamati.gov.bd"},
{"id":"Kawkhali","district_id":"Rangamati","name":"Kawkhali","bn_name":"কাউখালী","url":"kawkhali.rangamati.gov.bd"},
{"id":"Baghaichari","district_id":"Rangamati","name":"Baghaichari","bn_name":"বাঘাইছড়ি","url":"baghaichari.rangamati.gov.bd"},
{"id":"Barkal","district_id":"Rangamati","name":"Barkal","bn_name":"বরকল","url":"barkal.rangamati.gov.bd"},
{"id":"Langadu","district_id":"Rangamati","name":"Langadu","bn_name":"লংগদু","url":"langadu.rangamati.gov.bd"},
{"id":"Rajasthali","district_id":"Rangamati","name":"Rajasthali","bn_name":"রাজস্থলী","url":"rajasthali.rangamati.gov.bd"},
{"id":"Belaichari","district_id":"Rangamati","name":"Belaichari","bn_name":"বিলাইছড়ি","url":"belaichari.rangamati.gov.bd"},
{"id":"Juraichari","district_id":"Rangamati","name":"Juraichari","bn_name":"জুরাছড়ি","url":"juraichari.rangamati.gov.bd"},
{"id":"Naniarchar","district_id":"Rangamati","name":"Naniarchar","bn_name":"নানিয়ারচর","url":"naniarchar.rangamati.gov.bd"},
{"id":"NoakhaliSadar","district_id":"Noakhali","name":"Noakhali Sadar","bn_name":"নোয়াখালী সদর","url":"sadar.noakhali.gov.bd"},
{"id":"Companiganj","district_id":"Noakhali","name":"Companiganj","bn_name":"কোম্পানীগঞ্জ","url":"companiganj.noakhali.gov.bd"},
{"id":"Begumganj","district_id":"Noakhali","name":"Begumganj","bn_name":"বেগমগঞ্জ","url":"begumganj.noakhali.gov.bd"},
{"id":"Hatia","district_id":"Noakhali","name":"Hatia","bn_name":"হাতিয়া","url":"hatia.noakhali.gov.bd"},
{"id":"Subarnachar","district_id":"Noakhali","name":"Subarnachar","bn_name":"সুবর্ণচর","url":"subarnachar.noakhali.gov.bd"},
{"id":"Kabirhat","district_id":"Noakhali","name":"Kabirhat","bn_name":"কবিরহাট","url":"kabirhat.noakhali.gov.bd"},
{"id":"Senbug","district_id":"Noakhali","name":"Senbug","bn_name":"সেনবাগ","url":"senbug.noakhali.gov.bd"},
{"id":"Chatkhil","district_id":"Noakhali","name":"Chatkhil","bn_name":"চাটখিল","url":"chatkhil.noakhali.gov.bd"},
{"id":"Sonaimori","district_id":"Noakhali","name":"Sonaimori","bn_name":"সোনাইমুড়ী","url":"sonaimori.noakhali.gov.bd"},
{"id":"Haimchar","district_id":"Chandpur","name":"Haimchar","bn_name":"হাইমচর","url":"haimchar.chandpur.gov.bd"},
{"id":"Kachua","district_id":"Chandpur","name":"Kachua","bn_name":"কচুয়া","url":"kachua.chandpur.gov.bd"},
{"id":"Shahrasti","district_id":"Chandpur","name":"Shahrasti","bn_name":"শাহরাস্তি\t","url":"shahrasti.chandpur.gov.bd"},
{"id":"ChandpurSadar","district_id":"Chandpur","name":"Chandpur Sadar","bn_name":"চাঁদপুর সদর","url":"sadar.chandpur.gov.bd"},
{"id":"MatlabSouth","district_id":"Chandpur","name":"Matlab South","bn_name":"মতলব দক্ষিণ","url":"matlabsouth.chandpur.gov.bd"},
{"id":"Hajiganj","district_id":"Chandpur","name":"Hajiganj","bn_name":"হাজীগঞ্জ","url":"hajiganj.chandpur.gov.bd"},
{"id":"MatlabNorth","district_id":"Chandpur","name":"Matlab North","bn_name":"মতলব উত্তর","url":"matlabnorth.chandpur.gov.bd"},
{"id":"Faridgonj","district_id":"Chandpur","name":"Faridgonj","bn_name":"ফরিদগঞ্জ","url":"faridgonj.chandpur.gov.bd"},
{"id":"LakshmipurSadar","district_id":"Lakshmipur","name":"Lakshmipur Sadar","bn_name":"লক্ষ্মীপুর সদর","url":"sadar.lakshmipur.gov.bd"},
{"id":"Kamalnagar","district_id":"Lakshmipur","name":"Kamalnagar","bn_name":"কমলনগর","url":"kamalnagar.lakshmipur.gov.bd"},
{"id":"Raipur","district_id":"Lakshmipur","name":"Raipur","bn_name":"রায়পুর","url":"raipur.lakshmipur.gov.bd"},
{"id":"Ramgati","district_id":"Lakshmipur","name":"Ramgati","bn_name":"রামগতি","url":"ramgati.lakshmipur.gov.bd"},
{"id":"Ramganj","district_id":"Lakshmipur","name":"Ramganj","bn_name":"রামগঞ্জ","url":"ramganj.lakshmipur.gov.bd"},
{"id":"Rangunia","district_id":"Chattogram","name":"Rangunia","bn_name":"রাঙ্গুনিয়া","url":"rangunia.chittagong.gov.bd"},
{"id":"Sitakunda","district_id":"Chattogram","name":"Sitakunda","bn_name":"সীতাকুন্ড","url":"sitakunda.chittagong.gov.bd"},
{"id":"Mirsharai","district_id":"Chattogram","name":"Mirsharai","bn_name":"মীরসরাই","url":"mirsharai.chittagong.gov.bd"},
{"id":"Patiya","district_id":"Chattogram","name":"Patiya","bn_name":"পটিয়া","url":"patiya.chittagong.gov.bd"},
{"id":"Sandwip","district_id":"Chattogram","name":"Sandwip","bn_name":"সন্দ্বীপ","url":"sandwip.chittagong.gov.bd"},
{"id":"Banshkhali","district_id":"Chattogram","name":"Banshkhali","bn_name":"বাঁশখালী","url":"banshkhali.chittagong.gov.bd"},
{"id":"Boalkhali","district_id":"Chattogram","name":"Boalkhali","bn_name":"বোয়ালখালী","url":"boalkhali.chittagong.gov.bd"},
{"id":"Anwara","district_id":"Chattogram","name":"Anwara","bn_name":"আনোয়ারা","url":"anwara.chittagong.gov.bd"},
{"id":"Chandanaish","district_id":"Chattogram","name":"Chandanaish","bn_name":"চন্দনাইশ","url":"chandanaish.chittagong.gov.bd"},
{"id":"Satkania","district_id":"Chattogram","name":"Satkania","bn_name":"সাতকানিয়া","url":"satkania.chittagong.gov.bd"},
{"id":"Lohagara","district_id":"Chattogram","name":"Lohagara","bn_name":"লোহাগাড়া","url":"lohagara.chittagong.gov.bd"},
{"id":"Hathazari","district_id":"Chattogram","name":"Hathazari","bn_name":"হাটহাজারী","url":"hathazari.chittagong.gov.bd"},
{"id":"Fatikchhari","district_id":"Chattogram","name":"Fatikchhari","bn_name":"ফটিকছড়ি","url":"fatikchhari.chittagong.gov.bd"},
{"id":"Raozan","district_id":"Chattogram","name":"Raozan","bn_name":"রাউজান","url":"raozan.chittagong.gov.bd"},
{"id":"Karnafuli","district_id":"Chattogram","name":"Karnafuli","bn_name":"কর্ণফুলী","url":"karnafuli.chittagong.gov.bd"},
{"id":"CoxsbazarSadar","district_id":"Coxsbazar","name":"Coxsbazar Sadar","bn_name":"কক্সবাজার সদর","url":"sadar.coxsbazar.gov.bd"},
{"id":"Chakaria","district_id":"Coxsbazar","name":"Chakaria","bn_name":"চকরিয়া","url":"chakaria.coxsbazar.gov.bd"},
{"id":"Kutubdia","district_id":"Coxsbazar","name":"Kutubdia","bn_name":"কুতুবদিয়া","url":"kutubdia.coxsbazar.gov.bd"},
{"id":"Ukhiya","district_id":"Coxsbazar","name":"Ukhiya","bn_name":"উখিয়া","url":"ukhiya.coxsbazar.gov.bd"},
{"id":"Moheshkhali","district_id":"Coxsbazar","name":"Moheshkhali","bn_name":"মহেশখালী","url":"moheshkhali.coxsbazar.gov.bd"},
{"id":"Pekua","district_id":"Coxsbazar","name":"Pekua","bn_name":"পেকুয়া","url":"pekua.coxsbazar.gov.bd"},
{"id":"Ramu","district_id":"Coxsbazar","name":"Ramu","bn_name":"রামু","url":"ramu.coxsbazar.gov.bd"},
{"id":"Teknaf","district_id":"Coxsbazar","name":"Teknaf","bn_name":"টেকনাফ","url":"teknaf.coxsbazar.gov.bd"},
{"id":"KhagrachhariSadar","district_id":"Khagrachhari","name":"Khagrachhari Sadar","bn_name":"খাগড়াছড়ি সদর","url":"sadar.khagrachhari.gov.bd"},
{"id":"Dighinala","district_id":"Khagrachhari","name":"Dighinala","bn_name":"দিঘীনালা","url":"dighinala.khagrachhari.gov.bd"},
{"id":"Panchari","district_id":"Khagrachhari","name":"Panchari","bn_name":"পানছড়ি","url":"panchari.khagrachhari.gov.bd"},
{"id":"Laxmichhari","district_id":"Khagrachhari","name":"Laxmichhari","bn_name":"লক্ষীছড়ি","url":"laxmichhari.khagrachhari.gov.bd"},
{"id":"Mohalchari","district_id":"Khagrachhari","name":"Mohalchari","bn_name":"মহালছড়ি","url":"mohalchari.khagrachhari.gov.bd"},
{"id":"Manikchari","district_id":"Khagrachhari","name":"Manikchari","bn_name":"মানিকছড়ি","url":"manikchari.khagrachhari.gov.bd"},
{"id":"Ramgarh","district_id":"Khagrachhari","name":"Ramgarh","bn_name":"রামগড়","url":"ramgarh.khagrachhari.gov.bd"},
{"id":"Matiranga","district_id":"Khagrachhari","name":"Matiranga","bn_name":"মাটিরাঙ্গা","url":"matiranga.khagrachhari.gov.bd"},
{"id":"Guimara","district_id":"Khagrachhari","name":"Guimara","bn_name":"গুইমারা","url":"guimara.khagrachhari.gov.bd"},
{"id":"BandarbanSadar","district_id":"Bandarban","name":"Bandarban Sadar","bn_name":"বান্দরবান সদর","url":"sadar.bandarban.gov.bd"},
{"id":"Alikadam","district_id":"Bandarban","name":"Alikadam","bn_name":"আলীকদম","url":"alikadam.bandarban.gov.bd"},
{"id":"Naikhongchhari","district_id":"Bandarban","name":"Naikhongchhari","bn_name":"নাইক্ষ্যংছড়ি","url":"naikhongchhari.bandarban.gov.bd"},
{"id":"Rowangchhari","district_id":"Bandarban","name":"Rowangchhari","bn_name":"রোয়াংছড়ি","url":"rowangchhari.bandarban.gov.bd"},
{"id":"Lama","district_id":"Bandarban","name":"Lama","bn_name":"লামা","url":"lama.bandarban.gov.bd"},
{"id":"Ruma","district_id":"Bandarban","name":"Ruma","bn_name":"রুমা","url":"ruma.bandarban.gov.bd"},
{"id":"Thanchi","district_id":"Bandarban","name":"Thanchi","bn_name":"থানচি","url":"thanchi.bandarban.gov.bd"},
{"id":"Belkuchi","district_id":"Sirajganj","name":"Belkuchi","bn_name":"বেলকুচি","url":"belkuchi.sirajganj.gov.bd"},
{"id":"Chauhali","district_id":"Sirajganj","name":"Chauhali","bn_name":"চৌহালি","url":"chauhali.sirajganj.gov.bd"},
{"id":"Kamarkhand","district_id":"Sirajganj","name":"Kamarkhand","bn_name":"কামারখন্দ","url":"kamarkhand.sirajganj.gov.bd"},
{"id":"Kazipur","district_id":"Sirajganj","name":"Kazipur","bn_name":"কাজীপুর","url":"kazipur.sirajganj.gov.bd"},
{"id":"Raigonj","district_id":"Sirajganj","name":"Raigonj","bn_name":"রায়গঞ্জ","url":"raigonj.sirajganj.gov.bd"},
{"id":"Shahjadpur","district_id":"Sirajganj","name":"Shahjadpur","bn_name":"শাহজাদপুর","url":"shahjadpur.sirajganj.gov.bd"},
{"id":"SirajganjSadar","district_id":"Sirajganj","name":"Sirajganj Sadar","bn_name":"সিরাজগঞ্জ সদর","url":"sirajganjsadar.sirajganj.gov.bd"},
{"id":"Tarash","district_id":"Sirajganj","name":"Tarash","bn_name":"তাড়াশ","url":"tarash.sirajganj.gov.bd"},
{"id":"Ullapara","district_id":"Sirajganj","name":"Ullapara","bn_name":"উল্লাপাড়া","url":"ullapara.sirajganj.gov.bd"},
{"id":"Sujanagar","district_id":"Pabna","name":"Sujanagar","bn_name":"সুজানগর","url":"sujanagar.pabna.gov.bd"},
{"id":"Ishurdi","district_id":"Pabna","name":"Ishurdi","bn_name":"ঈশ্বরদী","url":"ishurdi.pabna.gov.bd"},
{"id":"Bhangura","district_id":"Pabna","name":"Bhangura","bn_name":"ভাঙ্গুড়া","url":"bhangura.pabna.gov.bd"},
{"id":"PabnaSadar","district_id":"Pabna","name":"Pabna Sadar","bn_name":"পাবনা সদর","url":"pabnasadar.pabna.gov.bd"},
{"id":"Bera","district_id":"Pabna","name":"Bera","bn_name":"বেড়া","url":"bera.pabna.gov.bd"},
{"id":"Atghoria","district_id":"Pabna","name":"Atghoria","bn_name":"আটঘরিয়া","url":"atghoria.pabna.gov.bd"},
{"id":"Chatmohar","district_id":"Pabna","name":"Chatmohar","bn_name":"চাটমোহর","url":"chatmohar.pabna.gov.bd"},
{"id":"Santhia","district_id":"Pabna","name":"Santhia","bn_name":"সাঁথিয়া","url":"santhia.pabna.gov.bd"},
{"id":"Faridpur","district_id":"Pabna","name":"Faridpur","bn_name":"ফরিদপুর","url":"faridpur.pabna.gov.bd"},
{"id":"Kahaloo","district_id":"Bogura","name":"Kahaloo","bn_name":"কাহালু","url":"kahaloo.bogra.gov.bd"},
{"id":"BograSadar","district_id":"Bogura","name":"Bogra Sadar","bn_name":"বগুড়া সদর","url":"sadar.bogra.gov.bd"},
{"id":"Shariakandi","district_id":"Bogura","name":"Shariakandi","bn_name":"সারিয়াকান্দি","url":"shariakandi.bogra.gov.bd"},
{"id":"Shajahanpur","district_id":"Bogura","name":"Shajahanpur","bn_name":"শাজাহানপুর","url":"shajahanpur.bogra.gov.bd"},
{"id":"Dupchanchia","district_id":"Bogura","name":"Dupchanchia","bn_name":"দুপচাচিঁয়া","url":"dupchanchia.bogra.gov.bd"},
{"id":"Adamdighi","district_id":"Bogura","name":"Adamdighi","bn_name":"আদমদিঘি","url":"adamdighi.bogra.gov.bd"},
{"id":"Nondigram","district_id":"Bogura","name":"Nondigram","bn_name":"নন্দিগ্রাম","url":"nondigram.bogra.gov.bd"},
{"id":"Sonatala","district_id":"Bogura","name":"Sonatala","bn_name":"সোনাতলা","url":"sonatala.bogra.gov.bd"},
{"id":"Dhunot","district_id":"Bogura","name":"Dhunot","bn_name":"ধুনট","url":"dhunot.bogra.gov.bd"},
{"id":"Gabtali","district_id":"Bogura","name":"Gabtali","bn_name":"গাবতলী","url":"gabtali.bogra.gov.bd"},
{"id":"Sherpur","district_id":"Bogura","name":"Sherpur","bn_name":"শেরপুর","url":"sherpur.bogra.gov.bd"},
{"id":"Shibganj","district_id":"Bogura","name":"Shibganj","bn_name":"শিবগঞ্জ","url":"shibganj.bogra.gov.bd"},
{"id":"Paba","district_id":"Rajshahi","name":"Paba","bn_name":"পবা","url":"paba.rajshahi.gov.bd"},
{"id":"Durgapur","district_id":"Rajshahi","name":"Durgapur","bn_name":"দুর্গাপুর","url":"durgapur.rajshahi.gov.bd"},
{"id":"Mohonpur","district_id":"Rajshahi","name":"Mohonpur","bn_name":"মোহনপুর","url":"mohonpur.rajshahi.gov.bd"},
{"id":"Charghat","district_id":"Rajshahi","name":"Charghat","bn_name":"চারঘাট","url":"charghat.rajshahi.gov.bd"},
{"id":"Puthia","district_id":"Rajshahi","name":"Puthia","bn_name":"পুঠিয়া","url":"puthia.rajshahi.gov.bd"},
{"id":"Bagha","district_id":"Rajshahi","name":"Bagha","bn_name":"বাঘা","url":"bagha.rajshahi.gov.bd"},
{"id":"Godagari","district_id":"Rajshahi","name":"Godagari","bn_name":"গোদাগাড়ী","url":"godagari.rajshahi.gov.bd"},
{"id":"Tanore","district_id":"Rajshahi","name":"Tanore","bn_name":"তানোর","url":"tanore.rajshahi.gov.bd"},
{"id":"Bagmara","district_id":"Rajshahi","name":"Bagmara","bn_name":"বাগমারা","url":"bagmara.rajshahi.gov.bd"},
{"id":"NatoreSadar","district_id":"Natore","name":"Natore Sadar","bn_name":"নাটোর সদর","url":"natoresadar.natore.gov.bd"},
{"id":"Singra","district_id":"Natore","name":"Singra","bn_name":"সিংড়া","url":"singra.natore.gov.bd"},
{"id":"Baraigram","district_id":"Natore","name":"Baraigram","bn_name":"বড়াইগ্রাম","url":"baraigram.natore.gov.bd"},
{"id":"Bagatipara","district_id":"Natore","name":"Bagatipara","bn_name":"বাগাতিপাড়া","url":"bagatipara.natore.gov.bd"},
{"id":"Lalpur","district_id":"Natore","name":"Lalpur","bn_name":"লালপুর","url":"lalpur.natore.gov.bd"},
{"id":"Gurudaspur","district_id":"Natore","name":"Gurudaspur","bn_name":"গুরুদাসপুর","url":"gurudaspur.natore.gov.bd"},
{"id":"Naldanga","district_id":"Natore","name":"Naldanga","bn_name":"নলডাঙ্গা","url":"naldanga.natore.gov.bd"},
{"id":"Akkelpur","district_id":"Joypurhat","name":"Akkelpur","bn_name":"আক্কেলপুর","url":"akkelpur.joypurhat.gov.bd"},
{"id":"Kalai","district_id":"Joypurhat","name":"Kalai","bn_name":"কালাই","url":"kalai.joypurhat.gov.bd"},
{"id":"Khetlal","district_id":"Joypurhat","name":"Khetlal","bn_name":"ক্ষেতলাল","url":"khetlal.joypurhat.gov.bd"},
{"id":"Panchbibi","district_id":"Joypurhat","name":"Panchbibi","bn_name":"পাঁচবিবি","url":"panchbibi.joypurhat.gov.bd"},
{"id":"JoypurhatSadar","district_id":"Joypurhat","name":"Joypurhat Sadar","bn_name":"জয়পুরহাট সদর","url":"joypurhatsadar.joypurhat.gov.bd"},
{"id":"ChapainawabganjSadar","district_id":"Chapainawabganj","name":"Chapainawabganj Sadar","bn_name":"চাঁপাইনবাবগঞ্জ সদর","url":"chapainawabganjsadar.chapainawabganj.gov.bd"},
{"id":"Gomostapur","district_id":"Chapainawabganj","name":"Gomostapur","bn_name":"গোমস্তাপুর","url":"gomostapur.chapainawabganj.gov.bd"},
{"id":"Nachol","district_id":"Chapainawabganj","name":"Nachol","bn_name":"নাচোল","url":"nachol.chapainawabganj.gov.bd"},
{"id":"Bholahat","district_id":"Chapainawabganj","name":"Bholahat","bn_name":"ভোলাহাট","url":"bholahat.chapainawabganj.gov.bd"},
{"id":"Shibganj","district_id":"Chapainawabganj","name":"Shibganj","bn_name":"শিবগঞ্জ","url":"shibganj.chapainawabganj.gov.bd"},
{"id":"Mohadevpur","district_id":"Naogaon","name":"Mohadevpur","bn_name":"মহাদেবপুর","url":"mohadevpur.naogaon.gov.bd"},
{"id":"Badalgachi","district_id":"Naogaon","name":"Badalgachi","bn_name":"বদলগাছী","url":"badalgachi.naogaon.gov.bd"},
{"id":"Patnitala","district_id":"Naogaon","name":"Patnitala","bn_name":"পত্নিতলা","url":"patnitala.naogaon.gov.bd"},
{"id":"Dhamoirhat","district_id":"Naogaon","name":"Dhamoirhat","bn_name":"ধামইরহাট","url":"dhamoirhat.naogaon.gov.bd"},
{"id":"Niamatpur","district_id":"Naogaon","name":"Niamatpur","bn_name":"নিয়ামতপুর","url":"niamatpur.naogaon.gov.bd"},
{"id":"Manda","district_id":"Naogaon","name":"Manda","bn_name":"মান্দা","url":"manda.naogaon.gov.bd"},
{"id":"Atrai","district_id":"Naogaon","name":"Atrai","bn_name":"আত্রাই","url":"atrai.naogaon.gov.bd"},
{"id":"Raninagar","district_id":"Naogaon","name":"Raninagar","bn_name":"রাণীনগর","url":"raninagar.naogaon.gov.bd"},
{"id":"NaogaonSadar","district_id":"Naogaon","name":"Naogaon Sadar","bn_name":"নওগাঁ সদর","url":"naogaonsadar.naogaon.gov.bd"},
{"id":"Porsha","district_id":"Naogaon","name":"Porsha","bn_name":"পোরশা","url":"porsha.naogaon.gov.bd"},
{"id":"Sapahar","district_id":"Naogaon","name":"Sapahar","bn_name":"সাপাহার","url":"sapahar.naogaon.gov.bd"},
{"id":"Manirampur","district_id":"Jashore","name":"Manirampur","bn_name":"মণিরামপুর","url":"manirampur.jessore.gov.bd"},
{"id":"Abhaynagar","district_id":"Jashore","name":"Abhaynagar","bn_name":"অভয়নগর","url":"abhaynagar.jessore.gov.bd"},
{"id":"Bagherpara","district_id":"Jashore","name":"Bagherpara","bn_name":"বাঘারপাড়া","url":"bagherpara.jessore.gov.bd"},
{"id":"Chougachha","district_id":"Jashore","name":"Chougachha","bn_name":"চৌগাছা","url":"chougachha.jessore.gov.bd"},
{"id":"Jhikargacha","district_id":"Jashore","name":"Jhikargacha","bn_name":"ঝিকরগাছা","url":"jhikargacha.jessore.gov.bd"},
{"id":"Keshabpur","district_id":"Jashore","name":"Keshabpur","bn_name":"কেশবপুর","url":"keshabpur.jessore.gov.bd"},
{"id":"JessoreSadar","district_id":"Jashore","name":"Jessore Sadar","bn_name":"যশোর সদর","url":"sadar.jessore.gov.bd"},
{"id":"Sharsha","district_id":"Jashore","name":"Sharsha","bn_name":"শার্শা","url":"sharsha.jessore.gov.bd"},
{"id":"Assasuni","district_id":"Satkhira","name":"Assasuni","bn_name":"আশাশুনি","url":"assasuni.satkhira.gov.bd"},
{"id":"Debhata","district_id":"Satkhira","name":"Debhata","bn_name":"দেবহাটা","url":"debhata.satkhira.gov.bd"},
{"id":"Kalaroa","district_id":"Satkhira","name":"Kalaroa","bn_name":"কলারোয়া","url":"kalaroa.satkhira.gov.bd"},
{"id":"Satkhira Sadar","district_id":"Satkhira","name":"Satkhira Sadar","bn_name":"সাতক্ষীরা সদর","url":"satkhirasadar.satkhira.gov.bd"},
{"id":"Shyamnagar","district_id":"Satkhira","name":"Shyamnagar","bn_name":"শ্যামনগর","url":"shyamnagar.satkhira.gov.bd"},
{"id":"Tala","district_id":"Satkhira","name":"Tala","bn_name":"তালা","url":"tala.satkhira.gov.bd"},
{"id":"Kaliganj","district_id":"Satkhira","name":"Kaliganj","bn_name":"কালিগঞ্জ","url":"kaliganj.satkhira.gov.bd"},
{"id":"Mujibnagar","district_id":"Meherpur","name":"Mujibnagar","bn_name":"মুজিবনগর","url":"mujibnagar.meherpur.gov.bd"},
{"id":"MeherpurSadar","district_id":"Meherpur","name":"Meherpur Sadar","bn_name":"মেহেরপুর সদর","url":"meherpursadar.meherpur.gov.bd"},
{"id":"Gangni","district_id":"Meherpur","name":"Gangni","bn_name":"গাংনী","url":"gangni.meherpur.gov.bd"},
{"id":"NarailSadar","district_id":"Narail","name":"Narail Sadar","bn_name":"নড়াইল সদর","url":"narailsadar.narail.gov.bd"},
{"id":"Lohagara","district_id":"Narail","name":"Lohagara","bn_name":"লোহাগড়া","url":"lohagara.narail.gov.bd"},
{"id":"Kalia","district_id":"Narail","name":"Kalia","bn_name":"কালিয়া","url":"kalia.narail.gov.bd"},
{"id":"ChuadangaSadar","district_id":"Chuadanga","name":"Chuadanga Sadar","bn_name":"চুয়াডাঙ্গা সদর","url":"chuadangasadar.chuadanga.gov.bd"},
{"id":"Alamdanga","district_id":"Chuadanga","name":"Alamdanga","bn_name":"আলমডাঙ্গা","url":"alamdanga.chuadanga.gov.bd"},
{"id":"Damurhuda","district_id":"Chuadanga","name":"Damurhuda","bn_name":"দামুড়হুদা","url":"damurhuda.chuadanga.gov.bd"},
{"id":"Jibannagar","district_id":"Chuadanga","name":"Jibannagar","bn_name":"জীবননগর","url":"jibannagar.chuadanga.gov.bd"},
{"id":"KushtiaSadar","district_id":"Kushtia","name":"Kushtia Sadar","bn_name":"কুষ্টিয়া সদর","url":"kushtiasadar.kushtia.gov.bd"},
{"id":"Kumarkhali","district_id":"Kushtia","name":"Kumarkhali","bn_name":"কুমারখালী","url":"kumarkhali.kushtia.gov.bd"},
{"id":"Khoksa","district_id":"Kushtia","name":"Khoksa","bn_name":"খোকসা","url":"khoksa.kushtia.gov.bd"},
{"id":"Mirpur","district_id":"Kushtia","name":"Mirpur","bn_name":"মিরপুর","url":"mirpurkushtia.kushtia.gov.bd"},
{"id":"Daulatpur","district_id":"Kushtia","name":"Daulatpur","bn_name":"দৌলতপুর","url":"daulatpur.kushtia.gov.bd"},
{"id":"Bheramara","district_id":"Kushtia","name":"Bheramara","bn_name":"ভেড়ামারা","url":"bheramara.kushtia.gov.bd"},
{"id":"Shalikha","district_id":"Magura","name":"Shalikha","bn_name":"শালিখা","url":"shalikha.magura.gov.bd"},
{"id":"Sreepur","district_id":"Magura","name":"Sreepur","bn_name":"শ্রীপুর","url":"sreepur.magura.gov.bd"},
{"id":"MaguraSadar","district_id":"Magura","name":"Magura Sadar","bn_name":"মাগুরা সদর","url":"magurasadar.magura.gov.bd"},
{"id":"Mohammadpur","district_id":"Magura","name":"Mohammadpur","bn_name":"মহম্মদপুর","url":"mohammadpur.magura.gov.bd"},
{"id":"Paikgasa","district_id":"Khulna","name":"Paikgasa","bn_name":"পাইকগাছা","url":"paikgasa.khulna.gov.bd"},
{"id":"Fultola","district_id":"Khulna","name":"Fultola","bn_name":"ফুলতলা","url":"fultola.khulna.gov.bd"},
{"id":"Digholia","district_id":"Khulna","name":"Digholia","bn_name":"দিঘলিয়া","url":"digholia.khulna.gov.bd"},
{"id":"Rupsha","district_id":"Khulna","name":"Rupsha","bn_name":"রূপসা","url":"rupsha.khulna.gov.bd"},
{"id":"Terokhada","district_id":"Khulna","name":"Terokhada","bn_name":"তেরখাদা","url":"terokhada.khulna.gov.bd"},
{"id":"Dumuria","district_id":"Khulna","name":"Dumuria","bn_name":"ডুমুরিয়া","url":"dumuria.khulna.gov.bd"},
{"id":"Botiaghata","district_id":"Khulna","name":"Botiaghata","bn_name":"বটিয়াঘাটা","url":"botiaghata.khulna.gov.bd"},
{"id":"Dakop","district_id":"Khulna","name":"Dakop","bn_name":"দাকোপ","url":"dakop.khulna.gov.bd"},
{"id":"Koyra","district_id":"Khulna","name":"Koyra","bn_name":"কয়রা","url":"koyra.khulna.gov.bd"},
{"id":"Fakirhat","district_id":"Bagerhat","name":"Fakirhat","bn_name":"ফকিরহাট","url":"fakirhat.bagerhat.gov.bd"},
{"id":"BagerhatSadar","district_id":"Bagerhat","name":"Bagerhat Sadar","bn_name":"বাগেরহাট সদর","url":"sadar.bagerhat.gov.bd"},
{"id":"Mollahat","district_id":"Bagerhat","name":"Mollahat","bn_name":"মোল্লাহাট","url":"mollahat.bagerhat.gov.bd"},
{"id":"Sarankhola","district_id":"Bagerhat","name":"Sarankhola","bn_name":"শরণখোলা","url":"sarankhola.bagerhat.gov.bd"},
{"id":"Rampal","district_id":"Bagerhat","name":"Rampal","bn_name":"রামপাল","url":"rampal.bagerhat.gov.bd"},
{"id":"Morrelganj","district_id":"Bagerhat","name":"Morrelganj","bn_name":"মোড়েলগঞ্জ","url":"morrelganj.bagerhat.gov.bd"},
{"id":"Kachua","district_id":"Bagerhat","name":"Kachua","bn_name":"কচুয়া","url":"kachua.bagerhat.gov.bd"},
{"id":"Mongla","district_id":"Bagerhat","name":"Mongla","bn_name":"মোংলা","url":"mongla.bagerhat.gov.bd"},
{"id":"Chitalmari","district_id":"Bagerhat","name":"Chitalmari","bn_name":"চিতলমারী","url":"chitalmari.bagerhat.gov.bd"},
{"id":"JhenaidahSadar","district_id":"Jhenaidah","name":"Jhenaidah Sadar","bn_name":"ঝিনাইদহ সদর","url":"sadar.jhenaidah.gov.bd"},
{"id":"Shailkupa","district_id":"Jhenaidah","name":"Shailkupa","bn_name":"শৈলকুপা","url":"shailkupa.jhenaidah.gov.bd"},
{"id":"Harinakundu","district_id":"Jhenaidah","name":"Harinakundu","bn_name":"হরিণাকুন্ডু","url":"harinakundu.jhenaidah.gov.bd"},
{"id":"Kaliganj","district_id":"Jhenaidah","name":"Kaliganj","bn_name":"কালীগঞ্জ","url":"kaliganj.jhenaidah.gov.bd"},
{"id":"Kotchandpur","district_id":"Jhenaidah","name":"Kotchandpur","bn_name":"কোটচাঁদপুর","url":"kotchandpur.jhenaidah.gov.bd"},
{"id":"Moheshpur","district_id":"Jhenaidah","name":"Moheshpur","bn_name":"মহেশপুর","url":"moheshpur.jhenaidah.gov.bd"},
{"id":"JhalakathiSadar","district_id":"Jhalakathi","name":"Jhalakathi Sadar","bn_name":"ঝালকাঠি সদর","url":"sadar.jhalakathi.gov.bd"},
{"id":"Kathalia","district_id":"Jhalakathi","name":"Kathalia","bn_name":"কাঠালিয়া","url":"kathalia.jhalakathi.gov.bd"},
{"id":"Nalchity","district_id":"Jhalakathi","name":"Nalchity","bn_name":"নলছিটি","url":"nalchity.jhalakathi.gov.bd"},
{"id":"Rajapur","district_id":"Jhalakathi","name":"Rajapur","bn_name":"রাজাপুর","url":"rajapur.jhalakathi.gov.bd"},
{"id":"Bauphal","district_id":"Patuakhali","name":"Bauphal","bn_name":"বাউফল","url":"bauphal.patuakhali.gov.bd"},
{"id":"PatuakhaliSadar","district_id":"Patuakhali","name":"Patuakhali Sadar","bn_name":"পটুয়াখালী সদর","url":"sadar.patuakhali.gov.bd"},
{"id":"Dumki","district_id":"Patuakhali","name":"Dumki","bn_name":"দুমকি","url":"dumki.patuakhali.gov.bd"},
{"id":"Dashmina","district_id":"Patuakhali","name":"Dashmina","bn_name":"দশমিনা","url":"dashmina.patuakhali.gov.bd"},
{"id":"Kalapara","district_id":"Patuakhali","name":"Kalapara","bn_name":"কলাপাড়া","url":"kalapara.patuakhali.gov.bd"},
{"id":"Mirzaganj","district_id":"Patuakhali","name":"Mirzaganj","bn_name":"মির্জাগঞ্জ","url":"mirzaganj.patuakhali.gov.bd"},
{"id":"Galachipa","district_id":"Patuakhali","name":"Galachipa","bn_name":"গলাচিপা","url":"galachipa.patuakhali.gov.bd"},
{"id":"Rangabali","district_id":"Patuakhali","name":"Rangabali","bn_name":"রাঙ্গাবালী","url":"rangabali.patuakhali.gov.bd"},
{"id":"PirojpurSadar","district_id":"Pirojpur","name":"Pirojpur Sadar","bn_name":"পিরোজপুর সদর","url":"sadar.pirojpur.gov.bd"},
{"id":"Nazirpur","district_id":"Pirojpur","name":"Nazirpur","bn_name":"নাজিরপুর","url":"nazirpur.pirojpur.gov.bd"},
{"id":"Kawkhali","district_id":"Pirojpur","name":"Kawkhali","bn_name":"কাউখালী","url":"kawkhali.pirojpur.gov.bd"},
{"id":"Zianagar","district_id":"Pirojpur","name":"Zianagar","bn_name":"জিয়ানগর","url":"zianagar.pirojpur.gov.bd"},
{"id":"Bhandaria","district_id":"Pirojpur","name":"Bhandaria","bn_name":"ভান্ডারিয়া","url":"bhandaria.pirojpur.gov.bd"},
{"id":"Mathbaria","district_id":"Pirojpur","name":"Mathbaria","bn_name":"মঠবাড়ীয়া","url":"mathbaria.pirojpur.gov.bd"},
{"id":"Nesarabad","district_id":"Pirojpur","name":"Nesarabad","bn_name":"নেছারাবাদ","url":"nesarabad.pirojpur.gov.bd"},
{"id":"BarisalSadar","district_id":"Barisal","name":"Barisal Sadar","bn_name":"বরিশাল সদর","url":"barisalsadar.barisal.gov.bd"},
{"id":"Bakerganj","district_id":"Barisal","name":"Bakerganj","bn_name":"বাকেরগঞ্জ","url":"bakerganj.barisal.gov.bd"},
{"id":"Babuganj","district_id":"Barisal","name":"Babuganj","bn_name":"বাবুগঞ্জ","url":"babuganj.barisal.gov.bd"},
{"id":"Wazirpur","district_id":"Barisal","name":"Wazirpur","bn_name":"উজিরপুর","url":"wazirpur.barisal.gov.bd"},
{"id":"Banaripara","district_id":"Barisal","name":"Banaripara","bn_name":"বানারীপাড়া","url":"banaripara.barisal.gov.bd"},
{"id":"Gournadi","district_id":"Barisal","name":"Gournadi","bn_name":"গৌরনদী","url":"gournadi.barisal.gov.bd"},
{"id":"Agailjhara","district_id":"Barisal","name":"Agailjhara","bn_name":"আগৈলঝাড়া","url":"agailjhara.barisal.gov.bd"},
{"id":"Mehendiganj","district_id":"Barisal","name":"Mehendiganj","bn_name":"মেহেন্দিগঞ্জ","url":"mehendiganj.barisal.gov.bd"},
{"id":"Muladi","district_id":"Barisal","name":"Muladi","bn_name":"মুলাদী","url":"muladi.barisal.gov.bd"},
{"id":"Hizla","district_id":"Barisal","name":"Hizla","bn_name":"হিজলা","url":"hizla.barisal.gov.bd"},
{"id":"BholaSadar","district_id":"Bhola","name":"Bhola Sadar","bn_name":"ভোলা সদর","url":"sadar.bhola.gov.bd"},
{"id":"Borhan_Sddin","district_id":"Bhola","name":"Borhan Sddin","bn_name":"বোরহান উদ্দিন","url":"borhanuddin.bhola.gov.bd"},
{"id":"Charfesson","district_id":"Bhola","name":"Charfesson","bn_name":"চরফ্যাশন","url":"charfesson.bhola.gov.bd"},
{"id":"Doulatkhan","district_id":"Bhola","name":"Doulatkhan","bn_name":"দৌলতখান","url":"doulatkhan.bhola.gov.bd"},
{"id":"Monpura","district_id":"Bhola","name":"Monpura","bn_name":"মনপুরা","url":"monpura.bhola.gov.bd"},
{"id":"Tazumuddin","district_id":"Bhola","name":"Tazumuddin","bn_name":"তজুমদ্দিন","url":"tazumuddin.bhola.gov.bd"},
{"id":"Lalmohan","district_id":"Bhola","name":"Lalmohan","bn_name":"লালমোহন","url":"lalmohan.bhola.gov.bd"},
{"id":"Amtali","district_id":"Barguna","name":"Amtali","bn_name":"আমতলী","url":"amtali.barguna.gov.bd"},
{"id":"BargunaSadar","district_id":"Barguna","name":"Barguna Sadar","bn_name":"বরগুনা সদর","url":"sadar.barguna.gov.bd"},
{"id":"Betagi","district_id":"Barguna","name":"Betagi","bn_name":"বেতাগী","url":"betagi.barguna.gov.bd"},
{"id":"Bamna","district_id":"Barguna","name":"Bamna","bn_name":"বামনা","url":"bamna.barguna.gov.bd"},
{"id":"Pathorghata","district_id":"Barguna","name":"Pathorghata","bn_name":"পাথরঘাটা","url":"pathorghata.barguna.gov.bd"},
{"id":"Taltali","district_id":"Barguna","name":"Taltali","bn_name":"তালতলি","url":"taltali.barguna.gov.bd"},
{"id":"Balaganj","district_id":"Sylhet","name":"Balaganj","bn_name":"বালাগঞ্জ","url":"balaganj.sylhet.gov.bd"},
{"id":"Beanibazar","district_id":"Sylhet","name":"Beanibazar","bn_name":"বিয়ানীবাজার","url":"beanibazar.sylhet.gov.bd"},
{"id":"Bishwanath","district_id":"Sylhet","name":"Bishwanath","bn_name":"বিশ্বনাথ","url":"bishwanath.sylhet.gov.bd"},
{"id":"Companiganj","district_id":"Sylhet","name":"Companiganj","bn_name":"কোম্পানীগঞ্জ","url":"companiganj.sylhet.gov.bd"},
{"id":"Fenchuganj","district_id":"Sylhet","name":"Fenchuganj","bn_name":"ফেঞ্চুগঞ্জ","url":"fenchuganj.sylhet.gov.bd"},
{"id":"Golapganj","district_id":"Sylhet","name":"Golapganj","bn_name":"গোলাপগঞ্জ","url":"golapganj.sylhet.gov.bd"},
{"id":"Gowainghat","district_id":"Sylhet","name":"Gowainghat","bn_name":"গোয়াইনঘাট","url":"gowainghat.sylhet.gov.bd"},
{"id":"Jaintiapur","district_id":"Sylhet","name":"Jaintiapur","bn_name":"জৈন্তাপুর","url":"jaintiapur.sylhet.gov.bd"},
{"id":"Kanaighat","district_id":"Sylhet","name":"Kanaighat","bn_name":"কানাইঘাট","url":"kanaighat.sylhet.gov.bd"},
{"id":"SylhetSadar","district_id":"Sylhet","name":"Sylhet Sadar","bn_name":"সিলেট সদর","url":"sylhetsadar.sylhet.gov.bd"},
{"id":"Zakiganj","district_id":"Sylhet","name":"Zakiganj","bn_name":"জকিগঞ্জ","url":"zakiganj.sylhet.gov.bd"},
{"id":"Dakshinsurma","district_id":"Sylhet","name":"Dakshinsurma","bn_name":"দক্ষিণ সুরমা","url":"dakshinsurma.sylhet.gov.bd"},
{"id":"Osmaninagar","district_id":"Sylhet","name":"Osmaninagar","bn_name":"ওসমানী নগর","url":"osmaninagar.sylhet.gov.bd"},
{"id":"Barlekha","district_id":"Moulvibazar","name":"Barlekha","bn_name":"বড়লেখা","url":"barlekha.moulvibazar.gov.bd"},
{"id":"Kamolganj","district_id":"Moulvibazar","name":"Kamolganj","bn_name":"কমলগঞ্জ","url":"kamolganj.moulvibazar.gov.bd"},
{"id":"Kulaura","district_id":"Moulvibazar","name":"Kulaura","bn_name":"কুলাউড়া","url":"kulaura.moulvibazar.gov.bd"},
{"id":"MoulvibazarSadar","district_id":"Moulvibazar","name":"Moulvibazar Sadar","bn_name":"মৌলভীবাজার সদর","url":"moulvibazarsadar.moulvibazar.gov.bd"},
{"id":"Rajnagar","district_id":"Moulvibazar","name":"Rajnagar","bn_name":"রাজনগর","url":"rajnagar.moulvibazar.gov.bd"},
{"id":"Sreemangal","district_id":"Moulvibazar","name":"Sreemangal","bn_name":"শ্রীমঙ্গল","url":"sreemangal.moulvibazar.gov.bd"},
{"id":"Juri","district_id":"Moulvibazar","name":"Juri","bn_name":"জুড়ী","url":"juri.moulvibazar.gov.bd"},
{"id":"Nabiganj","district_id":"Habiganj","name":"Nabiganj","bn_name":"নবীগঞ্জ","url":"nabiganj.habiganj.gov.bd"},
{"id":"Bahubal","district_id":"Habiganj","name":"Bahubal","bn_name":"বাহুবল","url":"bahubal.habiganj.gov.bd"},
{"id":"Ajmiriganj","district_id":"Habiganj","name":"Ajmiriganj","bn_name":"আজমিরীগঞ্জ","url":"ajmiriganj.habiganj.gov.bd"},
{"id":"Baniachong","district_id":"Habiganj","name":"Baniachong","bn_name":"বানিয়াচং","url":"baniachong.habiganj.gov.bd"},
{"id":"Lakhai","district_id":"Habiganj","name":"Lakhai","bn_name":"লাখাই","url":"lakhai.habiganj.gov.bd"},
{"id":"Chunarughat","district_id":"Habiganj","name":"Chunarughat","bn_name":"চুনারুঘাট","url":"chunarughat.habiganj.gov.bd"},
{"id":"HabiganjSadar","district_id":"Habiganj","name":"Habiganj Sadar","bn_name":"হবিগঞ্জ সদর","url":"habiganjsadar.habiganj.gov.bd"},
{"id":"Madhabpur","district_id":"Habiganj","name":"Madhabpur","bn_name":"মাধবপুর","url":"madhabpur.habiganj.gov.bd"},
{"id":"SunamganjSadar","district_id":"Sunamganj","name":"Sunamganj Sadar","bn_name":"সুনামগঞ্জ সদর","url":"sadar.sunamganj.gov.bd"},
{"id":"South_Sunamganj","district_id":"Sunamganj","name":"South Sunamganj","bn_name":"দক্ষিণ সুনামগঞ্জ","url":"southsunamganj.sunamganj.gov.bd"},
{"id":"Bishwambarpur","district_id":"Sunamganj","name":"Bishwambarpur","bn_name":"বিশ্বম্ভরপুর","url":"bishwambarpur.sunamganj.gov.bd"},
{"id":"Chhatak","district_id":"Sunamganj","name":"Chhatak","bn_name":"ছাতক","url":"chhatak.sunamganj.gov.bd"},
{"id":"Jagannathpur","district_id":"Sunamganj","name":"Jagannathpur","bn_name":"জগন্নাথপুর","url":"jagannathpur.sunamganj.gov.bd"},
{"id":"Dowarabazar","district_id":"Sunamganj","name":"Dowarabazar","bn_name":"দোয়ারাবাজার","url":"dowarabazar.sunamganj.gov.bd"},
{"id":"Tahirpur","district_id":"Sunamganj","name":"Tahirpur","bn_name":"তাহিরপুর","url":"tahirpur.sunamganj.gov.bd"},
{"id":"Dharmapasha","district_id":"Sunamganj","name":"Dharmapasha","bn_name":"ধর্মপাশা","url":"dharmapasha.sunamganj.gov.bd"},
{"id":"Jamalganj","district_id":"Sunamganj","name":"Jamalganj","bn_name":"জামালগঞ্জ","url":"jamalganj.sunamganj.gov.bd"},
{"id":"Shalla","district_id":"Sunamganj","name":"Shalla","bn_name":"শাল্লা","url":"shalla.sunamganj.gov.bd"},
{"id":"Derai","district_id":"Sunamganj","name":"Derai","bn_name":"দিরাই","url":"derai.sunamganj.gov.bd"},
{"id":"Belabo","district_id":"Narsingdi","name":"Belabo","bn_name":"বেলাবো","url":"belabo.narsingdi.gov.bd"},
{"id":"Monohardi","district_id":"Narsingdi","name":"Monohardi","bn_name":"মনোহরদী","url":"monohardi.narsingdi.gov.bd"},
{"id":"NarsingdiSadar","district_id":"Narsingdi","name":"Narsingdi Sadar","bn_name":"নরসিংদী সদর","url":"narsingdisadar.narsingdi.gov.bd"},
{"id":"Palash","district_id":"Narsingdi","name":"Palash","bn_name":"পলাশ","url":"palash.narsingdi.gov.bd"},
{"id":"Raipura","district_id":"Narsingdi","name":"Raipura","bn_name":"রায়পুরা","url":"raipura.narsingdi.gov.bd"},
{"id":"Shibpur","district_id":"Narsingdi","name":"Shibpur","bn_name":"শিবপুর","url":"shibpur.narsingdi.gov.bd"},
{"id":"Kaliganj","district_id":"Gazipur","name":"Kaliganj","bn_name":"কালীগঞ্জ","url":"kaliganj.gazipur.gov.bd"},
{"id":"Kaliakair","district_id":"Gazipur","name":"Kaliakair","bn_name":"কালিয়াকৈর","url":"kaliakair.gazipur.gov.bd"},
{"id":"Kapasia","district_id":"Gazipur","name":"Kapasia","bn_name":"কাপাসিয়া","url":"kapasia.gazipur.gov.bd"},
{"id":"GazipurSadar","district_id":"Gazipur","name":"Gazipur Sadar","bn_name":"গাজীপুর সদর","url":"sadar.gazipur.gov.bd"},
{"id":"Sreepur","district_id":"Gazipur","name":"Sreepur","bn_name":"শ্রীপুর","url":"sreepur.gazipur.gov.bd"},
{"id":"ShariatpurSadar","district_id":"Shariatpur","name":"Shariatpur Sadar","bn_name":"শরিয়তপুর সদর","url":"sadar.shariatpur.gov.bd"},
{"id":"Naria","district_id":"Shariatpur","name":"Naria","bn_name":"নড়িয়া","url":"naria.shariatpur.gov.bd"},
{"id":"Zajira","district_id":"Shariatpur","name":"Zajira","bn_name":"জাজিরা","url":"zajira.shariatpur.gov.bd"},
{"id":"Gosairhat","district_id":"Shariatpur","name":"Gosairhat","bn_name":"গোসাইরহাট","url":"gosairhat.shariatpur.gov.bd"},
{"id":"Bhedarganj","district_id":"Shariatpur","name":"Bhedarganj","bn_name":"ভেদরগঞ্জ","url":"bhedarganj.shariatpur.gov.bd"},
{"id":"Damudya","district_id":"Shariatpur","name":"Damudya","bn_name":"ডামুড্যা","url":"damudya.shariatpur.gov.bd"},
{"id":"Araihazar","district_id":"Narayanganj","name":"Araihazar","bn_name":"আড়াইহাজার","url":"araihazar.narayanganj.gov.bd"},
{"id":"Bandar","district_id":"Narayanganj","name":"Bandar","bn_name":"বন্দর","url":"bandar.narayanganj.gov.bd"},
{"id":"NarayanganjSadar","district_id":"Narayanganj","name":"Narayanganj Sadar","bn_name":"নারায়নগঞ্জ সদর","url":"narayanganjsadar.narayanganj.gov.bd"},
{"id":"Rupganj","district_id":"Narayanganj","name":"Rupganj","bn_name":"রূপগঞ্জ","url":"rupganj.narayanganj.gov.bd"},
{"id":"Sonargaon","district_id":"Narayanganj","name":"Sonargaon","bn_name":"সোনারগাঁ","url":"sonargaon.narayanganj.gov.bd"},
{"id":"Basail","district_id":"Tangail","name":"Basail","bn_name":"বাসাইল","url":"basail.tangail.gov.bd"},
{"id":"Bhuapur","district_id":"Tangail","name":"Bhuapur","bn_name":"ভুয়াপুর","url":"bhuapur.tangail.gov.bd"},
{"id":"Delduar","district_id":"Tangail","name":"Delduar","bn_name":"দেলদুয়ার","url":"delduar.tangail.gov.bd"},
{"id":"Ghatail","district_id":"Tangail","name":"Ghatail","bn_name":"ঘাটাইল","url":"ghatail.tangail.gov.bd"},
{"id":"Gopalpur","district_id":"Tangail","name":"Gopalpur","bn_name":"গোপালপুর","url":"gopalpur.tangail.gov.bd"},
{"id":"Madhupur","district_id":"Tangail","name":"Madhupur","bn_name":"মধুপুর","url":"madhupur.tangail.gov.bd"},
{"id":"Mirzapur","district_id":"Tangail","name":"Mirzapur","bn_name":"মির্জাপুর","url":"mirzapur.tangail.gov.bd"},
{"id":"Nagarpur","district_id":"Tangail","name":"Nagarpur","bn_name":"নাগরপুর","url":"nagarpur.tangail.gov.bd"},
{"id":"Sakhipur","district_id":"Tangail","name":"Sakhipur","bn_name":"সখিপুর","url":"sakhipur.tangail.gov.bd"},
{"id":"TangailSadar","district_id":"Tangail","name":"Tangail Sadar","bn_name":"টাঙ্গাইল সদর","url":"tangailsadar.tangail.gov.bd"},
{"id":"Kalihati","district_id":"Tangail","name":"Kalihati","bn_name":"কালিহাতী","url":"kalihati.tangail.gov.bd"},
{"id":"Dhanbari","district_id":"Tangail","name":"Dhanbari","bn_name":"ধনবাড়ী","url":"dhanbari.tangail.gov.bd"},
{"id":"Itna","district_id":"Kishoreganj","name":"Itna","bn_name":"ইটনা","url":"itna.kishoreganj.gov.bd"},
{"id":"Katiadi","district_id":"Kishoreganj","name":"Katiadi","bn_name":"কটিয়াদী","url":"katiadi.kishoreganj.gov.bd"},
{"id":"Bhairab","district_id":"Kishoreganj","name":"Bhairab","bn_name":"ভৈরব","url":"bhairab.kishoreganj.gov.bd"},
{"id":"Tarail","district_id":"Kishoreganj","name":"Tarail","bn_name":"তাড়াইল","url":"tarail.kishoreganj.gov.bd"},
{"id":"Hossainpur","district_id":"Kishoreganj","name":"Hossainpur","bn_name":"হোসেনপুর","url":"hossainpur.kishoreganj.gov.bd"},
{"id":"Pakundia","district_id":"Kishoreganj","name":"Pakundia","bn_name":"পাকুন্দিয়া","url":"pakundia.kishoreganj.gov.bd"},
{"id":"Kuliarchar","district_id":"Kishoreganj","name":"Kuliarchar","bn_name":"কুলিয়ারচর","url":"kuliarchar.kishoreganj.gov.bd"},
{"id":"KishoreganjSadar","district_id":"Kishoreganj","name":"Kishoreganj Sadar","bn_name":"কিশোরগঞ্জ সদর","url":"kishoreganjsadar.kishoreganj.gov.bd"},
{"id":"Karimgonj","district_id":"Kishoreganj","name":"Karimgonj","bn_name":"করিমগঞ্জ","url":"karimgonj.kishoreganj.gov.bd"},
{"id":"Bajitpur","district_id":"Kishoreganj","name":"Bajitpur","bn_name":"বাজিতপুর","url":"bajitpur.kishoreganj.gov.bd"},
{"id":"Austagram","district_id":"Kishoreganj","name":"Austagram","bn_name":"অষ্টগ্রাম","url":"austagram.kishoreganj.gov.bd"},
{"id":"Mithamoin","district_id":"Kishoreganj","name":"Mithamoin","bn_name":"মিঠামইন","url":"mithamoin.kishoreganj.gov.bd"},
{"id":"Nikli","district_id":"Kishoreganj","name":"Nikli","bn_name":"নিকলী","url":"nikli.kishoreganj.gov.bd"},
{"id":"Harirampur","district_id":"Manikganj","name":"Harirampur","bn_name":"হরিরামপুর","url":"harirampur.manikganj.gov.bd"},
{"id":"Saturia","district_id":"Manikganj","name":"Saturia","bn_name":"সাটুরিয়া","url":"saturia.manikganj.gov.bd"},
{"id":"ManikganjSadar","district_id":"Manikganj","name":"Manikganj Sadar","bn_name":"মানিকগঞ্জ সদর","url":"sadar.manikganj.gov.bd"},
{"id":"Gior","district_id":"Manikganj","name":"Gior","bn_name":"ঘিওর","url":"gior.manikganj.gov.bd"},
{"id":"Shibaloy","district_id":"Manikganj","name":"Shibaloy","bn_name":"শিবালয়","url":"shibaloy.manikganj.gov.bd"},
{"id":"Doulatpur","district_id":"Manikganj","name":"Doulatpur","bn_name":"দৌলতপুর","url":"doulatpur.manikganj.gov.bd"},
{"id":"Singiar","district_id":"Manikganj","name":"Singiar","bn_name":"সিংগাইর","url":"singiar.manikganj.gov.bd"},
{"id":"Dhaka_city","district_id":"Dhaka","name":"Dhaka(city)","bn_name":"ঢাকা সিটি","url":"city.dhaka.gov.bd"},
{"id":"Savar","district_id":"Dhaka","name":"Savar","bn_name":"সাভার","url":"savar.dhaka.gov.bd"},
{"id":"Dhamrai","district_id":"Dhaka","name":"Dhamrai","bn_name":"ধামরাই","url":"dhamrai.dhaka.gov.bd"},
{"id":"Keraniganj","district_id":"Dhaka","name":"Keraniganj","bn_name":"কেরাণীগঞ্জ","url":"keraniganj.dhaka.gov.bd"},
{"id":"Nawabganj","district_id":"Dhaka","name":"Nawabganj","bn_name":"নবাবগঞ্জ","url":"nawabganj.dhaka.gov.bd"},
{"id":"Dohar","district_id":"Dhaka","name":"Dohar","bn_name":"দোহার","url":"dohar.dhaka.gov.bd"},
{"id":"MunshiganjSadar","district_id":"Munshiganj","name":"Munshiganj Sadar","bn_name":"মুন্সিগঞ্জ সদর","url":"sadar.munshiganj.gov.bd"},
{"id":"Sreenagar","district_id":"Munshiganj","name":"Sreenagar","bn_name":"শ্রীনগর","url":"sreenagar.munshiganj.gov.bd"},
{"id":"Sirajdikhan","district_id":"Munshiganj","name":"Sirajdikhan","bn_name":"সিরাজদিখান","url":"sirajdikhan.munshiganj.gov.bd"},
{"id":"Louhajanj","district_id":"Munshiganj","name":"Louhajanj","bn_name":"লৌহজং","url":"louhajanj.munshiganj.gov.bd"},
{"id":"Gajaria","district_id":"Munshiganj","name":"Gajaria","bn_name":"গজারিয়া","url":"gajaria.munshiganj.gov.bd"},
{"id":"Tongibari","district_id":"Munshiganj","name":"Tongibari","bn_name":"টংগীবাড়ি","url":"tongibari.munshiganj.gov.bd"},
{"id":"RajbariSadar","district_id":"Rajbari","name":"Rajbari Sadar","bn_name":"রাজবাড়ী সদর","url":"sadar.rajbari.gov.bd"},
{"id":"Goalanda","district_id":"Rajbari","name":"Goalanda","bn_name":"গোয়ালন্দ","url":"goalanda.rajbari.gov.bd"},
{"id":"Pangsa","district_id":"Rajbari","name":"Pangsa","bn_name":"পাংশা","url":"pangsa.rajbari.gov.bd"},
{"id":"Baliakandi","district_id":"Rajbari","name":"Baliakandi","bn_name":"বালিয়াকান্দি","url":"baliakandi.rajbari.gov.bd"},
{"id":"Kalukhali","district_id":"Rajbari","name":"Kalukhali","bn_name":"কালুখালী","url":"kalukhali.rajbari.gov.bd"},
{"id":"MadaripurSadar","district_id":"Madaripur","name":"Madaripur Sadar","bn_name":"মাদারীপুর সদর","url":"sadar.madaripur.gov.bd"},
{"id":"Shibchar","district_id":"Madaripur","name":"Shibchar","bn_name":"শিবচর","url":"shibchar.madaripur.gov.bd"},
{"id":"Kalkini","district_id":"Madaripur","name":"Kalkini","bn_name":"কালকিনি","url":"kalkini.madaripur.gov.bd"},
{"id":"Rajoir","district_id":"Madaripur","name":"Rajoir","bn_name":"রাজৈর","url":"rajoir.madaripur.gov.bd"},
{"id":"Gopalganj","district_id":"Gopalganj","name":"Gopalganj Sadar","bn_name":"গোপালগঞ্জ সদর","url":"sadar.gopalganj.gov.bd"},
{"id":"Kashiani","district_id":"Gopalganj","name":"Kashiani","bn_name":"কাশিয়ানী","url":"kashiani.gopalganj.gov.bd"},
{"id":"Tungipara","district_id":"Gopalganj","name":"Tungipara","bn_name":"টুংগীপাড়া","url":"tungipara.gopalganj.gov.bd"},
{"id":"Kotalipara","district_id":"Gopalganj","name":"Kotalipara","bn_name":"কোটালীপাড়া","url":"kotalipara.gopalganj.gov.bd"},
{"id":"Muksudpur","district_id":"Gopalganj","name":"Muksudpur","bn_name":"মুকসুদপুর","url":"muksudpur.gopalganj.gov.bd"},
{"id":"Faridpur","district_id":"Faridpur","name":"Faridpur Sadar","bn_name":"ফরিদপুর সদর","url":"sadar.faridpur.gov.bd"},
{"id":"Alfadanga","district_id":"Faridpur","name":"Alfadanga","bn_name":"আলফাডাঙ্গা","url":"alfadanga.faridpur.gov.bd"},
{"id":"Boalmari","district_id":"Faridpur","name":"Boalmari","bn_name":"বোয়ালমারী","url":"boalmari.faridpur.gov.bd"},
{"id":"Sadarpur","district_id":"Faridpur","name":"Sadarpur","bn_name":"সদরপুর","url":"sadarpur.faridpur.gov.bd"},
{"id":"Nagarkanda","district_id":"Faridpur","name":"Nagarkanda","bn_name":"নগরকান্দা","url":"nagarkanda.faridpur.gov.bd"},
{"id":"Bhanga","district_id":"Faridpur","name":"Bhanga","bn_name":"ভাঙ্গা","url":"bhanga.faridpur.gov.bd"},
{"id":"Charbhadrasan","district_id":"Faridpur","name":"Charbhadrasan","bn_name":"চরভদ্রাসন","url":"charbhadrasan.faridpur.gov.bd"},
{"id":"Madhukhali","district_id":"Faridpur","name":"Madhukhali","bn_name":"মধুখালী","url":"madhukhali.faridpur.gov.bd"},
{"id":"Saltha","district_id":"Faridpur","name":"Saltha","bn_name":"সালথা","url":"saltha.faridpur.gov.bd"},
{"id":"PanchagarhSadar","district_id":"Panchagarh","name":"Panchagarh Sadar","bn_name":"পঞ্চগড় সদর","url":"panchagarhsadar.panchagarh.gov.bd"},
{"id":"Debiganj","district_id":"Panchagarh","name":"Debiganj","bn_name":"দেবীগঞ্জ","url":"debiganj.panchagarh.gov.bd"},
{"id":"Boda","district_id":"Panchagarh","name":"Boda","bn_name":"বোদা","url":"boda.panchagarh.gov.bd"},
{"id":"Atwari","district_id":"Panchagarh","name":"Atwari","bn_name":"আটোয়ারী","url":"atwari.panchagarh.gov.bd"},
{"id":"Tetulia","district_id":"Panchagarh","name":"Tetulia","bn_name":"তেতুলিয়া","url":"tetulia.panchagarh.gov.bd"},
{"id":"Nawabganj","district_id":"Dinajpur","name":"Nawabganj","bn_name":"নবাবগঞ্জ","url":"nawabganj.dinajpur.gov.bd"},
{"id":"Birganj","district_id":"Dinajpur","name":"Birganj","bn_name":"বীরগঞ্জ","url":"birganj.dinajpur.gov.bd"},
{"id":"Ghoraghat","district_id":"Dinajpur","name":"Ghoraghat","bn_name":"ঘোড়াঘাট","url":"ghoraghat.dinajpur.gov.bd"},
{"id":"Birampur","district_id":"Dinajpur","name":"Birampur","bn_name":"বিরামপুর","url":"birampur.dinajpur.gov.bd"},
{"id":"Parbatipur","district_id":"Dinajpur","name":"Parbatipur","bn_name":"পার্বতীপুর","url":"parbatipur.dinajpur.gov.bd"},
{"id":"Bochaganj","district_id":"Dinajpur","name":"Bochaganj","bn_name":"বোচাগঞ্জ","url":"bochaganj.dinajpur.gov.bd"},
{"id":"Kaharol","district_id":"Dinajpur","name":"Kaharol","bn_name":"কাহারোল","url":"kaharol.dinajpur.gov.bd"},
{"id":"Fulbari","district_id":"Dinajpur","name":"Fulbari","bn_name":"ফুলবাড়ী","url":"fulbari.dinajpur.gov.bd"},
{"id":"DinajpurSadar","district_id":"Dinajpur","name":"Dinajpur Sadar","bn_name":"দিনাজপুর সদর","url":"dinajpursadar.dinajpur.gov.bd"},
{"id":"Hakimpur","district_id":"Dinajpur","name":"Hakimpur","bn_name":"হাকিমপুর","url":"hakimpur.dinajpur.gov.bd"},
{"id":"Khansama","district_id":"Dinajpur","name":"Khansama","bn_name":"খানসামা","url":"khansama.dinajpur.gov.bd"},
{"id":"Birol","district_id":"Dinajpur","name":"Birol","bn_name":"বিরল","url":"birol.dinajpur.gov.bd"},
{"id":"Chirirbandar","district_id":"Dinajpur","name":"Chirirbandar","bn_name":"চিরিরবন্দর","url":"chirirbandar.dinajpur.gov.bd"},
{"id":"LalmonirhatSadar","district_id":"Lalmonirhat","name":"Lalmonirhat Sadar","bn_name":"লালমনিরহাট সদর","url":"sadar.lalmonirhat.gov.bd"},
{"id":"Kaliganj","district_id":"Lalmonirhat","name":"Kaliganj","bn_name":"কালীগঞ্জ","url":"kaliganj.lalmonirhat.gov.bd"},
{"id":"Hatibandha","district_id":"Lalmonirhat","name":"Hatibandha","bn_name":"হাতীবান্ধা","url":"hatibandha.lalmonirhat.gov.bd"},
{"id":"Patgram","district_id":"Lalmonirhat","name":"Patgram","bn_name":"পাটগ্রাম","url":"patgram.lalmonirhat.gov.bd"},
{"id":"Aditmari","district_id":"Lalmonirhat","name":"Aditmari","bn_name":"আদিতমারী","url":"aditmari.lalmonirhat.gov.bd"},
{"id":"Syedpur","district_id":"Nilphamari","name":"Syedpur","bn_name":"সৈয়দপুর","url":"syedpur.nilphamari.gov.bd"},
{"id":"Domar","district_id":"Nilphamari","name":"Domar","bn_name":"ডোমার","url":"domar.nilphamari.gov.bd"},
{"id":"Dimla","district_id":"Nilphamari","name":"Dimla","bn_name":"ডিমলা","url":"dimla.nilphamari.gov.bd"},
{"id":"Jaldhaka","district_id":"Nilphamari","name":"Jaldhaka","bn_name":"জলঢাকা","url":"jaldhaka.nilphamari.gov.bd"},
{"id":"Kishorganj","district_id":"Nilphamari","name":"Kishorganj","bn_name":"কিশোরগঞ্জ","url":"kishorganj.nilphamari.gov.bd"},
{"id":"NilphamariSadar","district_id":"Nilphamari","name":"Nilphamari Sadar","bn_name":"নীলফামারী সদর","url":"nilphamarisadar.nilphamari.gov.bd"},
{"id":"Sadullapur","district_id":"Gaibandha","name":"Sadullapur","bn_name":"সাদুল্লাপুর","url":"sadullapur.gaibandha.gov.bd"},
{"id":"GaibandhaSadar","district_id":"Gaibandha","name":"Gaibandha Sadar","bn_name":"গাইবান্ধা সদর","url":"gaibandhasadar.gaibandha.gov.bd"},
{"id":"Palashbari","district_id":"Gaibandha","name":"Palashbari","bn_name":"পলাশবাড়ী","url":"palashbari.gaibandha.gov.bd"},
{"id":"Saghata","district_id":"Gaibandha","name":"Saghata","bn_name":"সাঘাটা","url":"saghata.gaibandha.gov.bd"},
{"id":"Gobindaganj","district_id":"Gaibandha","name":"Gobindaganj","bn_name":"গোবিন্দগঞ্জ","url":"gobindaganj.gaibandha.gov.bd"},
{"id":"Sundarganj","district_id":"Gaibandha","name":"Sundarganj","bn_name":"সুন্দরগঞ্জ","url":"sundarganj.gaibandha.gov.bd"},
{"id":"Phulchari","district_id":"Gaibandha","name":"Phulchari","bn_name":"ফুলছড়ি","url":"phulchari.gaibandha.gov.bd"},
{"id":"ThakurgaonSadar","district_id":"Thakurgaon","name":"Thakurgaon Sadar","bn_name":"ঠাকুরগাঁও সদর","url":"thakurgaonsadar.thakurgaon.gov.bd"},
{"id":"Pirganj","district_id":"Thakurgaon","name":"Pirganj","bn_name":"পীরগঞ্জ","url":"pirganj.thakurgaon.gov.bd"},
{"id":"Ranisankail","district_id":"Thakurgaon","name":"Ranisankail","bn_name":"রাণীশংকৈল","url":"ranisankail.thakurgaon.gov.bd"},
{"id":"Haripur","district_id":"Thakurgaon","name":"Haripur","bn_name":"হরিপুর","url":"haripur.thakurgaon.gov.bd"},
{"id":"Baliadangi","district_id":"Thakurgaon","name":"Baliadangi","bn_name":"বালিয়াডাঙ্গী","url":"baliadangi.thakurgaon.gov.bd"},
{"id":"RangpurSadar","district_id":"Rangpur","name":"Rangpur Sadar","bn_name":"রংপুর সদর","url":"rangpursadar.rangpur.gov.bd"},
{"id":"Gangachara","district_id":"Rangpur","name":"Gangachara","bn_name":"গংগাচড়া","url":"gangachara.rangpur.gov.bd"},
{"id":"Taragonj","district_id":"Rangpur","name":"Taragonj","bn_name":"তারাগঞ্জ","url":"taragonj.rangpur.gov.bd"},
{"id":"Badargonj","district_id":"Rangpur","name":"Badargonj","bn_name":"বদরগঞ্জ","url":"badargonj.rangpur.gov.bd"},
{"id":"Mithapukur","district_id":"Rangpur","name":"Mithapukur","bn_name":"মিঠাপুকুর","url":"mithapukur.rangpur.gov.bd"},
{"id":"Pirgonj","district_id":"Rangpur","name":"Pirgonj","bn_name":"পীরগঞ্জ","url":"pirgonj.rangpur.gov.bd"},
{"id":"Kaunia","district_id":"Rangpur","name":"Kaunia","bn_name":"কাউনিয়া","url":"kaunia.rangpur.gov.bd"},
{"id":"Pirgacha","district_id":"Rangpur","name":"Pirgacha","bn_name":"পীরগাছা","url":"pirgacha.rangpur.gov.bd"},
{"id":"KurigramSadar","district_id":"Kurigram","name":"Kurigram Sadar","bn_name":"কুড়িগ্রাম সদর","url":"kurigramsadar.kurigram.gov.bd"},
{"id":"Nageshwari","district_id":"Kurigram","name":"Nageshwari","bn_name":"নাগেশ্বরী","url":"nageshwari.kurigram.gov.bd"},
{"id":"Bhurungamari","district_id":"Kurigram","name":"Bhurungamari","bn_name":"ভুরুঙ্গামারী","url":"bhurungamari.kurigram.gov.bd"},
{"id":"Phulbari","district_id":"Kurigram","name":"Phulbari","bn_name":"ফুলবাড়ী","url":"phulbari.kurigram.gov.bd"},
{"id":"Rajarhat","district_id":"Kurigram","name":"Rajarhat","bn_name":"রাজারহাট","url":"rajarhat.kurigram.gov.bd"},
{"id":"Ulipur","district_id":"Kurigram","name":"Ulipur","bn_name":"উলিপুর","url":"ulipur.kurigram.gov.bd"},
{"id":"Chilmari","district_id":"Kurigram","name":"Chilmari","bn_name":"চিলমারী","url":"chilmari.kurigram.gov.bd"},
{"id":"Rowmari","district_id":"Kurigram","name":"Rowmari","bn_name":"রৌমারী","url":"rowmari.kurigram.gov.bd"},
{"id":"Charrajibpur","district_id":"Kurigram","name":"Charrajibpur","bn_name":"চর রাজিবপুর","url":"charrajibpur.kurigram.gov.bd"},
{"id":"SherpurSadar","district_id":"Sherpur","name":"Sherpur Sadar","bn_name":"শেরপুর সদর","url":"sherpursadar.sherpur.gov.bd"},
{"id":"Nalitabari","district_id":"Sherpur","name":"Nalitabari","bn_name":"নালিতাবাড়ী","url":"nalitabari.sherpur.gov.bd"},
{"id":"Sreebordi","district_id":"Sherpur","name":"Sreebordi","bn_name":"শ্রীবরদী","url":"sreebordi.sherpur.gov.bd"},
{"id":"Nokla","district_id":"Sherpur","name":"Nokla","bn_name":"নকলা","url":"nokla.sherpur.gov.bd"},
{"id":"Jhenaigati","district_id":"Sherpur","name":"Jhenaigati","bn_name":"ঝিনাইগাতী","url":"jhenaigati.sherpur.gov.bd"},
{"id":"Fulbaria","district_id":"Mymensingh","name":"Fulbaria","bn_name":"ফুলবাড়ীয়া","url":"fulbaria.mymensingh.gov.bd"},
{"id":"Trishal","district_id":"Mymensingh","name":"Trishal","bn_name":"ত্রিশাল","url":"trishal.mymensingh.gov.bd"},
{"id":"Bhaluka","district_id":"Mymensingh","name":"Bhaluka","bn_name":"ভালুকা","url":"bhaluka.mymensingh.gov.bd"},
{"id":"Muktagacha","district_id":"Mymensingh","name":"Muktagacha","bn_name":"মুক্তাগাছা","url":"muktagacha.mymensingh.gov.bd"},
{"id":"Mymensingh","district_id":"Mymensingh","name":"Mymensingh Sadar","bn_name":"ময়মনসিংহ সদর","url":"mymensinghsadar.mymensingh.gov.bd"},
{"id":"Dhobaura","district_id":"Mymensingh","name":"Dhobaura","bn_name":"ধোবাউড়া","url":"dhobaura.mymensingh.gov.bd"},
{"id":"Phulpur","district_id":"Mymensingh","name":"Phulpur","bn_name":"ফুলপুর","url":"phulpur.mymensingh.gov.bd"},
{"id":"Haluaghat","district_id":"Mymensingh","name":"Haluaghat","bn_name":"হালুয়াঘাট","url":"haluaghat.mymensingh.gov.bd"},
{"id":"Gouripur","district_id":"Mymensingh","name":"Gouripur","bn_name":"গৌরীপুর","url":"gouripur.mymensingh.gov.bd"},
{"id":"Gafargaon","district_id":"Mymensingh","name":"Gafargaon","bn_name":"গফরগাঁও","url":"gafargaon.mymensingh.gov.bd"},
{"id":"Iswarganj","district_id":"Mymensingh","name":"Iswarganj","bn_name":"ঈশ্বরগঞ্জ","url":"iswarganj.mymensingh.gov.bd"},
{"id":"Nandail","district_id":"Mymensingh","name":"Nandail","bn_name":"নান্দাইল","url":"nandail.mymensingh.gov.bd"},
{"id":"Tarakanda","district_id":"Mymensingh","name":"Tarakanda","bn_name":"তারাকান্দা","url":"tarakanda.mymensingh.gov.bd"},
{"id":"JamalpurSadar","district_id":"Jamalpur","name":"Jamalpur Sadar","bn_name":"জামালপুর সদর","url":"jamalpursadar.jamalpur.gov.bd"},
{"id":"Melandah","district_id":"Jamalpur","name":"Melandah","bn_name":"মেলান্দহ","url":"melandah.jamalpur.gov.bd"},
{"id":"Islampur","district_id":"Jamalpur","name":"Islampur","bn_name":"ইসলামপুর","url":"islampur.jamalpur.gov.bd"},
{"id":"Dewangonj","district_id":"Jamalpur","name":"Dewangonj","bn_name":"দেওয়ানগঞ্জ","url":"dewangonj.jamalpur.gov.bd"},
{"id":"Sarishabari","district_id":"Jamalpur","name":"Sarishabari","bn_name":"সরিষাবাড়ী","url":"sarishabari.jamalpur.gov.bd"},
{"id":"Madarganj","district_id":"Jamalpur","name":"Madarganj","bn_name":"মাদারগঞ্জ","url":"madarganj.jamalpur.gov.bd"},
{"id":"Bokshiganj","district_id":"Jamalpur","name":"Bokshiganj","bn_name":"বকশীগঞ্জ","url":"bokshiganj.jamalpur.gov.bd"},
{"id":"Barhatta","district_id":"Netrokona","name":"Barhatta","bn_name":"বারহাট্টা","url":"barhatta.netrokona.gov.bd"},
{"id":"Durgapur","district_id":"Netrokona","name":"Durgapur","bn_name":"দুর্গাপুর","url":"durgapur.netrokona.gov.bd"},
{"id":"Kendua","district_id":"Netrokona","name":"Kendua","bn_name":"কেন্দুয়া","url":"kendua.netrokona.gov.bd"},
{"id":"Atpara","district_id":"Netrokona","name":"Atpara","bn_name":"আটপাড়া","url":"atpara.netrokona.gov.bd"},
{"id":"Madan","district_id":"Netrokona","name":"Madan","bn_name":"মদন","url":"madan.netrokona.gov.bd"},
{"id":"Khaliajuri","district_id":"Netrokona","name":"Khaliajuri","bn_name":"খালিয়াজুরী","url":"khaliajuri.netrokona.gov.bd"},
{"id":"Kalmakanda","district_id":"Netrokona","name":"Kalmakanda","bn_name":"কলমাকান্দা","url":"kalmakanda.netrokona.gov.bd"},
{"id":"Mohongonj","district_id":"Netrokona","name":"Mohongonj","bn_name":"মোহনগঞ্জ","url":"mohongonj.netrokona.gov.bd"},
{"id":"Purbadhala","district_id":"Netrokona","name":"Purbadhala","bn_name":"পূর্বধলা","url":"purbadhala.netrokona.gov.bd"},
{"id":"NetrokonaSadar","district_id":"Netrokona","name":"Netrokona Sadar","bn_name":"নেত্রকোণা সদর","url":"netrokonasadar.netrokona.gov.bd"}
]
